CREATE TABLE locations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    latitude   DECIMAL(11, 8) DEFAULT 0                NOT NULL,
    longitude  DECIMAL(11, 8) DEFAULT 0                NOT NULL,
    address    TEXT,
    city       VARCHAR(100),
    district   VARCHAR(100),
    place_name VARCHAR(250),
    timezone   VARCHAR(20),
    CONSTRAINT pk_locations PRIMARY KEY (id)
);
