server:
    port: 8081

spring:
  application:
    name: locations-service

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:geo_db}
    username: ${DB_USERNAME:geo_user}
    password: ${DB_PASSWORD:geo_pass}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
