CREATE TABLE communities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    is_private  BOOLEAN                                 NOT NULL,
    cover_url   TEXT,
    CONSTRAINT pk_communities PRIMARY KEY (id)
);

CREATE TABLE community_member
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT                                  NOT NULL,
    community_id BIGINT                                  NOT NULL,
    member_role  VARCHAR(20) DEFAULT 'member' CHECK (member_role IN ('member', 'organizer')),
    CONSTRAINT pk_community_member PRIMARY KEY (id)
);

CREATE TABLE community_organizer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    community_id BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_community_organizer PRIMARY KEY (id)
);

CREATE TABLE community_tags
(
    community_id BIGINT NOT NULL,
    tag_id       BIGINT NOT NULL,
    CONSTRAINT pk_communitytags PRIMARY KEY (community_id, tag_id)
);

CREATE TABLE event_attendances
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    user_id           BIGINT                                  NOT NULL,
    event_id          BIGINT                                  NOT NULL,
    attendance_status VARCHAR(20) DEFAULT 'pending' CHECK (attendance_status IN ('pending', 'confirmed', 'cancelled', 'attended')),
    CONSTRAINT pk_event_attendances PRIMARY KEY (id)
);

CREATE TABLE event_tags
(
    event_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL,
    CONSTRAINT pk_eventtags PRIMARY KEY (event_id, tag_id)
);

CREATE TABLE events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT                                  NOT NULL,
    title            VARCHAR(255),
    description      TEXT,
    start_datetime   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_datetime     TIMESTAMP WITHOUT TIME ZONE,
    location_id      BIGINT                                  NOT NULL,
    price            DECIMAL(10, 2) DEFAULT 0,
    currency         VARCHAR(3),
    poster_url       TEXT,
    event_status     VARCHAR(20)    DEFAULT 'draft' CHECK (event_status IN ('published', 'cancelled', 'completed', 'draft')),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    max_participants INTEGER,
    is_online        BOOLEAN,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE locations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    latitude   DECIMAL(11, 8) DEFAULT 0                NOT NULL,
    longitude  DECIMAL(11, 8) DEFAULT 0                NOT NULL,
    address    TEXT,
    city       VARCHAR(100),
    district   VARCHAR(100),
    place_name VARCHAR(250),
    timezone   VARCHAR(20),
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    message    TEXT,
    type       VARCHAR(20) DEFAULT 'system' CHECK (type IN ('event', 'system', 'message')),
    is_read    BOOLEAN,
    event_id   BIGINT,
    action_url TEXT,
    priority   VARCHAR(20) DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high')),
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                  NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    rating     INTEGER,
    comment    TEXT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY                      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    email         VARCHAR(255)                                                 NOT NULL,
    password_hash VARCHAR(255)                                                 NOT NULL,
    phone         VARCHAR(20),
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    avatar_url    TEXT,
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    is_banned     BOOLEAN,
    role          VARCHAR(20) DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE community_member
    ADD CONSTRAINT FK_COMMUNITY_MEMBER_ON_COMMUNITY FOREIGN KEY (community_id) REFERENCES communities (id);

ALTER TABLE community_member
    ADD CONSTRAINT FK_COMMUNITY_MEMBER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE community_organizer
    ADD CONSTRAINT FK_COMMUNITY_ORGANIZER_ON_COMMUNITY FOREIGN KEY (community_id) REFERENCES communities (id);

ALTER TABLE community_organizer
    ADD CONSTRAINT FK_COMMUNITY_ORGANIZER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE event_attendances
    ADD CONSTRAINT FK_EVENT_ATTENDANCES_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE event_attendances
    ADD CONSTRAINT FK_EVENT_ATTENDANCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE community_tags
    ADD CONSTRAINT fk_comtag_on_community FOREIGN KEY (community_id) REFERENCES communities (id);

ALTER TABLE community_tags
    ADD CONSTRAINT fk_comtag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);

ALTER TABLE event_tags
    ADD CONSTRAINT fk_evetag_on_event FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE event_tags
    ADD CONSTRAINT fk_evetag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);