CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY                      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    email         VARCHAR(255)                                                 NOT NULL,
    password_hash VARCHAR(255)                                                 NOT NULL,
    phone         VARCHAR(20),
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    avatar_url    TEXT,
    last_login    TIMESTAMP WITHOUT TIME ZONE,
    is_banned     BOOLEAN,
    role          VARCHAR(20) DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
